/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 scene.gltf --transform 
Files: scene.gltf [8.13KB] > /Users/dellwatson/Downloads/ready_for_trailers/orchid_manta_-_spaceship_pbr/scene-transformed.glb [1.23MB] (-15088%)
Author: iggy-design (https://sketchfab.com/iggy-design)
License: SKETCHFAB Editorial (https://sketchfab.com/licenses)
Source: https://sketchfab.com/3d-models/orchid-manta-spaceship-pbr-cb321955546a43328cc73d336c1fe2a8
Title: Orchid Manta - spaceship PBR
*/

import React, { useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";
import GLB_MODEL from "./scene-transformed.glb";

export function Model(props) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF(GLB_MODEL);
  const { actions } = useAnimations(animations, group);
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="RootNode" scale={0.013}>
          <group
            name="Orchid_Manta"
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}>
            <mesh
              name="Orchid_Manta_Material_0"
              geometry={nodes.Orchid_Manta_Material_0.geometry}
              material={materials.Material}
            />
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload(GLB_MODEL);
