/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 phoenix_bird.glb --transform 
Files: phoenix_bird.glb [1.63MB] > /Users/dellwatson/Desktop/vitejs-vite-arzf67/src/_backend/conveyance/phoenix/phoenix_bird-transformed.glb [462.76KB] (72%)
Author: NORBERTO-3D (https://sketchfab.com/norberto3d)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/phoenix-bird-844ba0cf144a413ea92c779f18912042
Title: phoenix bird
*/

import React, { useRef, useEffect } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";
import GLB_MODEL from "./phoenix_bird-transformed.glb";

export function Model(props) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF(GLB_MODEL);
  const { actions } = useAnimations(animations, group);

  // Play all animations when the component mounts
  useEffect(() => {
    actions && Object.values(actions).forEach((action) => action.play());
    return () =>
      actions && Object.values(actions).forEach((action) => action.stop());
  }, [actions]); // Depend on actions to re-run this effect if they change

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <primitive object={nodes._rootJoint} />
        <skinnedMesh
          name="Object_7"
          geometry={nodes.Object_7.geometry}
          material={materials.MatI_Ride_FengHuang_01a}
          skeleton={nodes.Object_7.skeleton}
          position={[-0.625, 0, -17.137]}
          rotation={[0, 0.053, 0]}
        />
        <skinnedMesh
          name="Object_8"
          geometry={nodes.Object_8.geometry}
          material={materials.MatI_Ride_FengHuang_01b}
          skeleton={nodes.Object_8.skeleton}
          position={[-0.625, 0, -17.137]}
          rotation={[0, 0.053, 0]}
        />
      </group>
    </group>
  );
}

useGLTF.preload(GLB_MODEL);
