/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 scene.gltf --transform 
Files: scene.gltf [5.36KB] > /Users/dellwatson/Downloads/ready_for_trailers/sparrow_fighter_spacecraft/scene-transformed.glb [548.72KB] (-10137%)
Author: CGPitbull (https://sketchfab.com/CGPitbull)
License: SKETCHFAB Standard (https://sketchfab.com/licenses)
Source: https://sketchfab.com/3d-models/sparrow-fighter-spacecraft-9877408b0bbc4fcdbe8335e2379bbed5
Title: SPARROW Fighter Spacecraft
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import GLB_MODEL from "./scene-transformed.glb";

export function Model(props) {
  const { nodes, materials } = useGLTF(GLB_MODEL);
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Sparrow_Fighter_Sparrow_Fighter_0.geometry}
        material={materials.Sparrow_Fighter}
        position={[0, 0.911, 0]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.01}
      />
    </group>
  );
}

useGLTF.preload(GLB_MODEL);
