/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 scene.gltf --transform 
Files: scene.gltf [15.94KB] > /Users/dellwatson/Downloads/ready_for_trailers/alien_spaceship_-_big_fighter/scene-transformed.glb [198.22KB] (-1144%)
Author: trimitek (https://sketchfab.com/trimitek)
License: SKETCHFAB Standard (https://sketchfab.com/licenses)
Source: https://sketchfab.com/3d-models/alien-spaceship-big-fighter-f3ec4847aa014e27bfcc9f2c188c889a
Title: Alien Spaceship - Big Fighter
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import GLB_MODEL from "./scene-transformed.glb";

export function Model(props) {
  const { nodes, materials } = useGLTF(GLB_MODEL);
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={
          nodes.alien_battle_fighter_ancient_procedural_stone_3_0.geometry
        }
        material={materials.ancient_procedural_stone_3}
        position={[0, 0, -5.531]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.01}
      />
      <mesh
        geometry={nodes.alien_battle_fighter_black_glass_0.geometry}
        material={materials.black_glass}
        position={[0, 0, -5.531]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.01}
      />
      <mesh
        geometry={nodes.alien_battle_fighter_engines_0.geometry}
        material={materials.engines}
        position={[0, 0, -5.531]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.01}
      />
      <mesh
        geometry={nodes.alien_battle_fighter_pulse_0.geometry}
        material={materials.pulse}
        position={[0, 0, -5.531]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.01}
      />
    </group>
  );
}

useGLTF.preload(GLB_MODEL);
