/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 ship.gltf --transform 
Files: ship.gltf [97.78KB] > /Users/dellwatson/Downloads/12615e53-bb5a-4b5b-a004-436a004a580e/public/ship-transformed.glb [9.95KB] (90%)
Author: TheMuffinCoder (https://sketchfab.com/themuffincoder)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/delta-break-renault-s-t1-dab401ce6ec649a29ee0856051a111c2
Title: [Delta Break] Renault (S, T1)
*/

import React, { useLayoutEffect } from "react";
import { useGLTF } from "@react-three/drei";
import GLB_MODEL from "./ship-transformed.glb";

export function Model(props) {
  const { nodes, materials } = useGLTF(GLB_MODEL);
  useLayoutEffect(() => {
    Object.values(materials).forEach((material) => {
      material.roughness = 0;
    });
  }, []);
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes["Renault_(S,_T1)_0"].geometry}
        material={materials.PaletteMaterial001}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[0.892, 1, 1]}
      />
      <mesh
        geometry={nodes["Renault_(S,_T1)_4"].geometry}
        material={materials.PaletteMaterial002}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[0.892, 1, 1]}
      />
      <mesh
        geometry={nodes["Renault_(S,_T1)_5"].geometry}
        material={materials.PaletteMaterial003}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[0.892, 1, 1]}
      />
    </group>
  );
}

useGLTF.preload(GLB_MODEL);
