/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 animated_dragon.glb --transform 
Files: animated_dragon.glb [17.49MB] > /Users/dellwatson/Desktop/vitejs-vite-arzf67/src/_backend/conveyance/animatedDragon/animated_dragon-transformed.glb [2.81MB] (84%)
Author: LasquetiSpice (https://sketchfab.com/LasquetiSpice)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/animated-dragon-three-motion-loops-eca98cf6cd084c1596cecf716e110c29
Title: Animated Dragon Three Motion Loops
*/

import React, { useRef, useEffect } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";
import GLB_MODEL from "./animated_dragon-transformed.glb";

export function Model(props) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF(GLB_MODEL);
  const { actions } = useAnimations(animations, group);

  // Play all animations when the component mounts
  useEffect(() => {
    actions && Object.values(actions).forEach((action) => action.play());
    return () =>
      actions && Object.values(actions).forEach((action) => action.stop());
  }, [actions]); // Depend on actions to re-run this effect if they change

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <primitive object={nodes.GLTF_created_0_rootJoint} />
        <skinnedMesh
          name="Object_228"
          geometry={nodes.Object_228.geometry}
          material={materials.material_0}
          skeleton={nodes.Object_228.skeleton}
          scale={0.073}
        />
      </group>
    </group>
  );
}

useGLTF.preload(GLB_MODEL);
